feat: Enables ironic idrac interface
rackerlabs/understack pull request #161
Opened 2024-07-15 21:41 UTC by nicholaskuechler

Reference: https://docs.openstack.org/ironic/latest/admin/drivers/idrac.html

Error I'm seeing when attempting to use idrac: 
```
No valid host was found. Reason: No conductor service registered which supports driver idrac for conductor group "". Ensure the driver is valid and enabled. (HTTP 400)
```

2024-07-16 22:24 UTC, ctria requested changes

2024-07-16 22:24 UTC, ctria commented on components/ironic/aio-values.yaml
> +      enabled_raid_interfaces: no-raid,redfish,idrac-redfish,idrac-redfish
idrac-redfish is listed twice

2024-07-16 22:28 UTC, nicholaskuechler commented on components/ironic/aio-values.yaml
> +      enabled_raid_interfaces: no-raid,redfish,idrac-redfish,idrac-redfish
fixed, thanks

2024-07-17 15:55 UTC, ctria approved these changes

2024-07-17 15:55 UTC, merged